services:
  - type: web
    name: skin-disease-classification
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Streamlit.py --server.port $PORT --server.address 0.0.0.0
